# Generated by Django 5.1.5 on 2025-02-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schematics',
            old_name='shcematic_json',
            new_name='schematic_json',
        ),
    ]
