# Generated by Django 5.1.5 on 2025-02-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_shcematic_json_schematics_schematic_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schematics',
            old_name='group_id',
            new_name='group',
        ),
    ]
