# Generated by Django 5.1.5 on 2025-06-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cleantime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleantime',
            name='group',
        ),
    ]
