# Generated by Django 5.1.5 on 2025-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_cleantime_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleantime',
            name='zone_id',
            field=models.CharField(default='default_zone', max_length=100),
        ),
    ]
